HomeWork commit
IfroloffI/HomeWork1 pull request #1
Opened 2023-11-05 17:30 UTC by IfroloffI

All working. Review, please=)

2023-11-10 19:14 UTC, Yu-Leo requested changes
Как поправишь замечания, напиши, пожалуйста, в комментариях к PR слово "ИСПРАВЛЕНО", чтобы я видел, что всё готово и можно ещё раз глянуть.

2023-11-10 19:14 UTC, Yu-Leo commented on task-1/main.go
> +	c := math.Sqrt(float64(a*a + b*b))
Тут можно использовать библиотечную ф-цию [Hypot](https://pkg.go.dev/math#Hypot)

2023-11-10 19:14 UTC, Yu-Leo commented on task-2/main.go
> +}
Здорово, что разобрался и самостоятельно написал реализацию [интерфейса](https://pkg.go.dev/sort#Interface)!

Можно сделать проще и читаемее, если использовать [sort.Ints](https://pkg.go.dev/sort#Ints)

2023-11-10 19:14 UTC, Yu-Leo commented on task-3/main.go
> +	var arr []int
Лучше сразу выделить память на нужное число эллементов (если оно известно, а в данном случае это так), а не аппендить каждый раз в цикле

2023-11-10 19:14 UTC, Yu-Leo commented on task-4/main.go
> +func createMatrix(arr *[][]int, size *int) {
Тут можно без указателей. Тем более - на `int`

2023-11-10 19:14 UTC, Yu-Leo commented on task-4/main.go
> +	}
Перемудрил.

Очевидный минус такого решения - выделение лишней памяти для второй матрицы.

Можно обойтись без неё и проверять симметричность матрицы относительно главной диагонали прямо в той матрице, которую ты считал

2023-11-10 19:14 UTC, Yu-Leo commented on task-5/main.go
> +	str = strings.Replace(str, "1", "one", -1)
Можно использовать [ReplaceAll](https://pkg.go.dev/strings#ReplaceAll), так будет более читаемо

2023-11-10 19:14 UTC, Yu-Leo commented on task-6/main.go
> +	var setStr = make(map[string]string)
Можно использовать `map[string]struct{}`, поскольку нам не нужно хранить значения по ключам. Такой вариант будет занимать меньше памяти и будет более читаемым

2023-11-10 19:14 UTC, Yu-Leo commented on task-6/main.go
> +	splitedStr[len(splitedStr)-1] = splitedStr[len(splitedStr)-1][0 : len(last)-2] // "someNumber\n" -> "someNumber"
Сложночитаемый кусок. Думаю, имеет смысл вынести генерацию "чистого" списка слов в отдельную ф-цию

2023-11-11 10:20 UTC, IfroloffI commented
ИСПРАВЛЕНО

2023-11-11 11:29 UTC, Yu-Leo approved these changes
Аппрув! 🎆

ДЗ принято, можешь смерджить ветки

2023-11-11 15:09 UTC, merged